version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/00-schema.sql:ro
      - ./backend/seed.sql:/docker-entrypoint-initdb.d/01-seed.sql:ro

  api:
    build: ./backend
    # Use a lightweight Node base if you prefer; here we install via package.json
    environment:
      NODE_ENV: production
      PORT: 8080
      DATABASE_URL: ${DATABASE_URL}
      CORS_ORIGIN: ${CORS_ORIGIN}
    ports:
      - "8080:8080"
    depends_on:
      - db

  web:
    build: ./frontend
    environment:
      VITE_API_BASE_URL: ${PUBLIC_API_BASE_URL}
    ports:
      - "5173:80"
    depends_on:
      - api

volumes:
  db_data: